services:
  app:
    build: .
    container_name: sitescope-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Mount storage directory for screenshots and persistent data
      - ./storage:/app/storage
    #env_file:
    #  - .env
    #environment:
    #  - ENV_VALUES_HERE=IF_YOU_WANT
      # Override DATABASE_URL for Docker network connection
      #- DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    # Add security capabilities for Puppeteer
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    # Health check to ensure the app is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
